services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  airflow-webserver:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__WEBSERVER__RBAC: 'true'
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_airflow_secret_123"
      # dbt environment variables
      DBT_PROFILES_DIR: /opt/airflow/.dbt
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/.dbt/service-account-key.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ../../marketplace_dbt:/opt/airflow/dbt
      - ./dbt_profiles:/opt/airflow/.dbt
      - ~/.keys/service-account-key.json:/opt/airflow/.dbt/service-account-key.json:ro
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: ["airflow", "webserver"]
    restart: always

  airflow-scheduler:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__WEBSERVER__SECRET_KEY: "my_airflow_secret_123"
      # dbt environment variables
      DBT_PROFILES_DIR: /opt/airflow/.dbt
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/.dbt/service-account-key.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ../../marketplace_dbt:/opt/airflow/dbt
      - ./dbt_profiles:/opt/airflow/.dbt
      - ~/.keys/service-account-key.json:/opt/airflow/.dbt/service-account-key.json:ro
      - ./logs:/opt/airflow/logs
    command: ["airflow", "scheduler"]
    restart: always

volumes:
  postgres_data: